### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by taitruong** [software-developer-org/typescript-template#1]
Readme
# install
- use Node LTS
- git exercises: use this [bootcamp] for further exercises on git and GitHub
- remove typescript install
- install vscode 
-- recommended extensions
--- ESLint
--- prettier
--- prettier eslint
--- git history

# Move template to your-repo
- create on GitHub a new repo e.g. 'myrepo'
- on bash:
````
> move template to myrepo folder
> cd myrepo
> remove remote repo linked to template
> add remote repo (for pull and push) to myrepo
> git pull
> git commit
> git push

gitignore: pacakge-lock.json

**Comment by RouvenGonzalez** [comment]
add conifg file for vs code to template 
with debug and eslint conifgs enabled
