### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by taitruong** [software-developer-org/typescript-template#21]
For duplicating a repo you say
> remove the temporary local repository ...

Why do I need remove it? Look at this output after bare cloning:
```
$ cd ng-react-demo/
/d/workspace/ng-react-demo (BARE:master)
```
See the message: (BARE:master). Explain this. That is why you have to remove and clone it. Then the message is different...

Also you forgot the next step. You have to git clone the new repo.

**Comment by KlugeCh** [comment]
Done
